apiVersion: v1
kind: ConfigMap
metadata:
  name: volume-cm
data:
  # Database connection config
  my.config.db: |
    database: mysql
    database_uri: mysql://localhost:3306
---
apiVersion: v1
kind: Pod
metadata:
  name: cm-pod
  labels:
    name: cm-pod
spec:
  containers:
  - name: cm-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
      - configMapRef:
          name: volume-cm
    volumeMounts:
      - name: volume
        mountPath: "/etc/volume"
        readOnly: true
  volumes:
    - name: volume
      configMap:
        name: volume-cm
