apiVersion: v1
kind: Pod
metadata:
  name: volumes-pod
  labels:
    name: volumes-pod
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
      - mountPath: "/my-data"
        name: "my-hostpath-vol"
  volumes:
    - name: "my-hostpath-vol"
      hostPath:
        path: "/var/lib/two-persist"