apiVersion: v1
kind: Service
metadata:
  name: jupyter-svc
  namespace: jupyter
  labels:
    app: jupyter-app
spec:
  selector:
    app: jupyter-pods
  ports:
  - port: 8888
    nodePort: 30000
    protocol: TCP
  type: NodePort