apiVersion: v1
kind: Endpoints
metadata:
  name: my-endpoints-svc
subsets:
  - addresses:
      - ip: 77.68.88.76 # IIS
      # - ip: "172.17.0.3" # apache
      # - ip: "172.17.0.4" # nginx
    ports:
      - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-endpoints-svc
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
