apiVersion: v1
kind: Pod
metadata:
  name: secret-optional-pod
  labels:
    name: secret-optional-pod
spec:
  containers:
  - name: secret-optional-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
      - secretRef:
          name: volume-secret
          optional: true
    volumeMounts:
      - name: volume
        mountPath: "/etc/volume"
        readOnly: true
  volumes:
    - name: volume
      secret:
        secretName: volume-secret
        optional: true