apiVersion: v1
kind: Secret
metadata:
  name: volume-secret
data:
  user: YWRtaW4=
  pass: bXktcGFzcy0xMjM=
stringData:
  my-database-name: mariadb
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
  labels:
    name: secret-pod
spec:
  containers:
  - name: secret-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    envFrom:
      - secretRef:
          name: volume-secret
    volumeMounts:
      - name: volume
        mountPath: "/etc/volume"
        readOnly: true
  volumes:
    - name: volume
      secret:
        secretName: volume-secret