apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    apps: backend
spec:
  containers:
  - name: redis-container
    image: redis
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"