apiVersion: v1
kind: Pod
metadata:
  name: tomcat-pod
  labels:
    apps: app-java
spec:
  containers:
  - name: tomcat-container
    image: tomcat
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"