apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sts
spec:
  selector:
    matchLabels:
      app: nginx-app
  serviceName: sts-service
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: my-pv
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: my-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
