apiVersion: v1
kind: Pod
metadata:
  name: my-pod-web-server
  labels:
    name: my-pod-web-server
    apps: my-app
    tier: frontend
spec:
  containers:
  - name: my-container-nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
