apiVersion: v1
kind: Service
metadata:
  name: my-eps-svc
spec:
  ports:
  - port: 80
    name: http
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: apache-eps
  labels:
    kubernetes.io/service-name: my-eps-svc
addressType: IPv4
endpoints:
  - addresses:
      - "172.17.0.4"
ports:
  - name: http
    port: 80
    protocol: TCP
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: nginx-eps
  labels:
    kubernetes.io/service-name: my-eps-svc
addressType: IPv4
endpoints:
  - addresses:
      - "172.17.0.3"
ports:
  - name: http
    port: 80
    protocol: TCP